// Seeded random schema-10 JSON -> native bake/render geometry parity against
// summaries generated by js/track-render-geometry.js.
#include <algorithm>
#include <array>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <string>

#include "Track.hpp"
#include "nlohmann/json.hpp"

using nlohmann::json;
using namespace tox;

namespace {
int failures = 0;
double worstRatio = 0.0;
std::string worstField;

void check(bool condition, const std::string& message) {
  if (condition) return;
  ++failures;
  std::cerr << "FAIL: " << message << '\n';
}

json readJson(const std::filesystem::path& path) {
  std::ifstream input(path);
  json value;
  input >> value;
  return value;
}

std::string kindName(GeometryKind kind) {
  switch (kind) {
    case GeometryKind::PathSurface: return "PathSurface";
    case GeometryKind::PathShell: return "PathShell";
    case GeometryKind::PathRail: return "PathRail";
    case GeometryKind::MeshSurface: return "MeshSurface";
    case GeometryKind::MeshRail: return "MeshRail";
    case GeometryKind::ZoneSurface: return "ZoneSurface";
  }
  return "unknown";
}

void checkClose(double got, double want, double atol, double rtol, const std::string& message) {
  const double delta = std::fabs(got - want);
  const double tolerance = atol + rtol * std::fabs(want);
  const double ratio = tolerance > 0 ? delta / tolerance : delta;
  if (ratio > worstRatio) {
    worstRatio = ratio;
    worstField = message;
  }
  check(std::isfinite(got) && delta <= tolerance,
        message + ": got " + std::to_string(got) + ", want " + std::to_string(want) +
            ", tolerance " + std::to_string(tolerance));
}

struct BatchStats {
  std::array<double, 3> min{std::numeric_limits<double>::infinity(), std::numeric_limits<double>::infinity(),
                            std::numeric_limits<double>::infinity()};
  std::array<double, 3> max{-std::numeric_limits<double>::infinity(), -std::numeric_limits<double>::infinity(),
                            -std::numeric_limits<double>::infinity()};
  std::array<double, 2> uvMin{std::numeric_limits<double>::infinity(), std::numeric_limits<double>::infinity()};
  std::array<double, 2> uvMax{-std::numeric_limits<double>::infinity(), -std::numeric_limits<double>::infinity()};
  std::array<double, 3> centroid{0, 0, 0};
  std::array<double, 3> orientedArea{0, 0, 0};
  double area{0};
};

BatchStats summarize(const GeometryBatch& batch, const std::string& label) {
  BatchStats out;
  for (const RenderVertex& vertex : batch.vertices) {
    const std::array<double, 3> p{vertex.position.x, vertex.position.y, vertex.position.z};
    const std::array<double, 3> n{vertex.normal.x, vertex.normal.y, vertex.normal.z};
    const std::array<double, 2> uv{vertex.uv.x, vertex.uv.y};
    for (int k = 0; k < 3; ++k) {
      out.min[k] = std::min(out.min[k], p[k]);
      out.max[k] = std::max(out.max[k], p[k]);
      check(std::isfinite(p[k]) && std::isfinite(n[k]), label + ": finite position/normal");
    }
    for (int k = 0; k < 2; ++k) {
      out.uvMin[k] = std::min(out.uvMin[k], uv[k]);
      out.uvMax[k] = std::max(out.uvMax[k], uv[k]);
      check(std::isfinite(uv[k]), label + ": finite UV");
    }
    check(std::fabs(vertex.normal.length() - 1.0) <= 1e-9, label + ": unit normal");
    check(vertex.rgba.r == 1 && vertex.rgba.g == 1 && vertex.rgba.b == 1 && vertex.rgba.a == 1,
          label + ": opaque white RGBA");
  }

  std::array<double, 3> firstMoment{0, 0, 0};
  check(batch.indices.size() % 3 == 0, label + ": triangle index count");
  for (std::size_t i = 0; i + 2 < batch.indices.size(); i += 3) {
    const std::uint32_t ia = batch.indices[i], ib = batch.indices[i + 1], ic = batch.indices[i + 2];
    if (ia >= batch.vertices.size() || ib >= batch.vertices.size() || ic >= batch.vertices.size()) {
      check(false, label + ": index is in range");
      continue;
    }
    const Vec3& a = batch.vertices[ia].position;
    const Vec3& b = batch.vertices[ib].position;
    const Vec3& c = batch.vertices[ic].position;
    const Vec3 u = Vec3().subVectors(b, a);
    const Vec3 v = Vec3().subVectors(c, a);
    const Vec3 cross = Vec3().crossVectors(u, v);
    const double triangleArea = cross.length() / 2.0;
    out.area += triangleArea;
    const std::array<double, 3> av{a.x, a.y, a.z}, bv{b.x, b.y, b.z}, cv{c.x, c.y, c.z};
    const std::array<double, 3> cr{cross.x, cross.y, cross.z};
    for (int k = 0; k < 3; ++k) {
      firstMoment[k] += triangleArea * (av[k] + bv[k] + cv[k]) / 3.0;
      out.orientedArea[k] += cr[k] / 2.0;
    }
  }
  if (out.area > 0)
    for (int k = 0; k < 3; ++k) out.centroid[k] = firstMoment[k] / out.area;
  return out;
}

void checkArray(const std::array<double, 3>& got, const json& want, double atol, double rtol,
                const std::string& message) {
  for (int k = 0; k < 3; ++k) checkClose(got[k], want[k].get<double>(), atol, rtol, message + "." + std::to_string(k));
}

void checkArray(const std::array<double, 2>& got, const json& want, double atol, double rtol,
                const std::string& message) {
  for (int k = 0; k < 2; ++k) checkClose(got[k], want[k].get<double>(), atol, rtol, message + "." + std::to_string(k));
}
}  // namespace

int main(int argc, char** argv) {
  if (argc != 2) {
    std::cerr << "usage: random_geometry_parity <random-fixture-directory>\n";
    return 2;
  }
  const std::filesystem::path fixtureDir = argv[1];
  const json manifest = readJson(fixtureDir / "manifest.json");
  const json expected = readJson(fixtureDir / "expected" / "geometry-summary.json");
  check(manifest.size() >= 4, "random corpus has multiple seeds");

  for (const json& entry : manifest) {
    const std::string file = entry.at("file").get<std::string>();
    const std::string label = file + " seed=" + std::to_string(entry.at("seed").get<std::uint32_t>());
    const TrackLoadResult loaded = Track::fromFile(fixtureDir / file);
    check(static_cast<bool>(loaded), label + " loads and bakes: " + loaded.error);
    if (!loaded) continue;
    check(loaded.warnings.empty(), label + " has no native warnings");
    check(expected.contains(file), label + " has a JavaScript geometry oracle");
    if (!expected.contains(file)) continue;
    const json& oracle = expected.at(file);
    const Track& track = *loaded.track;
    check(track.paths.size() == oracle.at("pathCount").get<std::size_t>(), label + " path count");
    check(track.meshRegions.size() == oracle.at("placementCount").get<std::size_t>(), label + " mesh placement count");
    check(track.geometry.size() == oracle.at("batchCount").get<std::size_t>(), label + " geometry batch count");
    check(oracle.at("warningCount").get<int>() == 0, label + " JS bake has no warnings");

    for (const json& expectedBatch : oracle.at("batches")) {
      const std::string id = expectedBatch.at("id").get<std::string>();
      const auto found = std::find_if(track.geometry.begin(), track.geometry.end(),
                                      [&](const GeometryBatch& batch) { return batch.id == id; });
      check(found != track.geometry.end(), label + " batch exists: " + id);
      if (found == track.geometry.end()) continue;
      const GeometryBatch& batch = *found;
      const std::string batchLabel = label + " " + id;
      check(kindName(batch.kind) == expectedBatch.at("kind").get<std::string>(), batchLabel + " kind");
      check(batch.materialKey == expectedBatch.at("materialKey").get<std::string>(), batchLabel + " material key");
      check(batch.vertices.size() == expectedBatch.at("vertexCount").get<std::size_t>(), batchLabel + " vertex count");
      check(batch.indices.size() == expectedBatch.at("indexCount").get<std::size_t>(), batchLabel + " index count");
      check(batch.hasUv == expectedBatch.at("hasUv").get<bool>(), batchLabel + " UV flag");
      if (expectedBatch.at("texture").is_null()) {
        check(!batch.texture, batchLabel + " has no texture");
      } else {
        check(batch.texture.has_value(), batchLabel + " has texture");
        if (batch.texture) {
          check(batch.texture->assetId == expectedBatch.at("texture").at("assetId").get<std::string>() &&
                    batch.texture->tile == expectedBatch.at("texture").at("tile").get<int>(),
                batchLabel + " texture binding");
        }
      }

      const BatchStats stats = summarize(batch, batchLabel);
      checkArray(stats.min, expectedBatch.at("min"), 2e-9, 1e-12, batchLabel + ".min");
      checkArray(stats.max, expectedBatch.at("max"), 2e-9, 1e-12, batchLabel + ".max");
      checkClose(stats.area, expectedBatch.at("area").get<double>(), 2e-8, 2e-12, batchLabel + ".area");
      checkArray(stats.centroid, expectedBatch.at("centroid"), 2e-9, 1e-12, batchLabel + ".centroid");
      checkArray(stats.orientedArea, expectedBatch.at("orientedArea"), 2e-8, 2e-12, batchLabel + ".orientedArea");
      if (batch.hasUv) {
        checkArray(stats.uvMin, expectedBatch.at("uvMin"), 2e-9, 1e-12, batchLabel + ".uvMin");
        checkArray(stats.uvMax, expectedBatch.at("uvMax"), 2e-9, 1e-12, batchLabel + ".uvMax");
      }
    }
  }

  if (failures) {
    std::cerr << failures << " random geometry parity failure(s); worst ratio " << worstRatio << " at " << worstField << '\n';
    return 1;
  }
  std::cout << "PASS: " << manifest.size() << " seeded random schema-10 tracks match JS geometry"
            << " (worst ratio " << worstRatio << " at " << worstField << ")\n";
  return 0;
}
